# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

steps:

- task: UseDotNet@2
  displayName: 'Use .NET SDK'
  inputs:
    version: 8.0.x

- task: CmdLine@2
  displayName: 'Install Nuke'
  inputs:
    script: |
      dotnet tool install --global Nuke.GlobalTool --version 6.0.3

- script: nuke --target RunTests --configuration Release
  displayName: 'Run Unit Tests'

- script: nuke --target Package --configuration Release
  displayName: 'Generate Nuget Package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/src/Avalonia.Controls.TreeDataGrid/bin/Release/'
    ArtifactName: 'drop'
    publishLocation: 'Container'
