name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install Nuke    
        run: dotnet tool install --global Nuke.GlobalTool --version 6.0.1

      - name: Build
        run: nuke --target Package --configuration Release

      - name: Test
        run: nuke --target RunTests --configuration Release
